name: Build XMRig

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake \
            automake libtool autoconf

      - name: Build static deps
        run: |
          cd scripts
          ./build_deps.sh

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DXMRIG_DEPS=scripts/deps -DDONATE_LEVEL=0
          make -j$(nproc)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-linux-static
          path: build/xmrig

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout xmrig-deps
        run: git clone https://github.com/xmrig/xmrig-deps.git c:/xmrig-deps

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DXMRIG_DEPS=c:\xmrig-deps\msvc2022\x64 -DDONATE_LEVEL=0
          cmake --build . --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: xmrig-windows
          path: build/Release/xmrig.exe
